### ISSUE TITLE
Add CSS reset

### ISSUE THREAD

**Issue by WanderB0y** [CodeMNLOfficial/canva-landing-page-clone#10]
# CSS Reset Usage Guide

CSS Reset is a set of CSS rules that reset the styling of all HTML elements to a consistent baseline. Before using a CSS reset, every browser has its default styles that can make your web pages look different across browsers. By applying a CSS reset, you can ensure that your design looks the same in all browsers.

Here's a simple guide to implementing a CSS reset in your projects.

## Table of Contents

- [Introduction](#introduction)
- [Installation](#installation)
- [Usage](#usage)
- [Customizing](#customizing)
- [Contributing](#contributing)
- [License](#license)
- [Credits](#credits)

## Introduction

Incorporating a CSS reset helps in reducing browser inconsistencies in things like default line heights, margins, font sizes of headings, and so on.

## Installation

To use a CSS reset, you can either include it in your HTML or import it into your CSS. Below are the two common methods:

### Method 1: Link Directly

Include the following line in the `<head>` section of your HTML document:

```html
<link rel="stylesheet" href="path/to/css/reset.css">
```

Replace `path/to/css/reset.css` with the actual path to your CSS reset file.

### Method 2: Import in CSS

In your main CSS file, add the following at the very top:

```css
@import url('path/to/css/reset.css');
```

Again, replace `path/to/css/reset.css` with the path to your CSS reset file.

## Usage

Once you've included the CSS reset file using one of the methods above, it will automatically strip out the default browser styling. From there, you can start styling your elements as you normally would, without worrying about browser inconsistencies.

Here's a basic example of what might be in a CSS reset file:

```css
/* CSS Reset */
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
```

## Customizing

You can customize your CSS reset by editing the reset file directly. Just make sure to keep the basic reset rules at the top of your CSS file, so they get applied before any other styles.

## Contributing

If you'd like to contribute to the development of the CSS reset file, please follow the project's contributing guidelines.

## License

This project is typically released under the MIT License. See the LICENSE file for details.

## Credits

Acknowledge those who have contributed to the project or creators of the original reset.css if you are using a variant.

**Note**: Replace `path/to/css/reset.css` with the actual path to your CSS reset file in your project and be sure to tailor the README to fit your specific CSS reset implementation if it differs from the provided example.
