### ISSUE TITLE
Add custom css properties and utility classes

### ISSUE THREAD

**Issue by WanderB0y** [CodeMNLOfficial/canva-landing-page-clone#23]
# CSS Custom Properties and Utility Classes

This document explains how to set up custom properties and utility classes in CSS for your project. We'll cover the reasons why these techniques are important and provide step-by-step instructions for implementing them.

## Table of Contents

- [Introduction](#introduction)
- [Why Custom Properties?](#why-custom-properties)
- [Why Utility Classes?](#why-utility-classes)
- [Setting Up Custom Properties](#setting-up-custom-properties)
- [Creating Utility Classes](#creating-utility-classes)
- [Best Practices](#best-practices)
- [Examples](#examples)
- [Contributing](#contributing)

## Introduction

Custom properties (often referred to as CSS variables) and utility classes are powerful tools in modern CSS that allow for more dynamic, organized, and reusable code.

### Why Custom Properties?

Custom properties allow you to:

- Store values for reuse throughout your document, making it easy to update multiple styles from a single place.
- Create a consistent theme and easily switch between themes.
- Enhance readability of your CSS by using meaningful names.

### Why Utility Classes?

Utility classes are small, single-purpose classes that:

- Increase the efficiency of your styling process.
- Help maintain consistency in design by reusing common style patterns.
- Reduce the need for custom CSS by providing a toolkit of functional classes.
- Make your HTML more readable by abstracting complex CSS.

## Setting Up Custom Properties

To create custom properties:

1. Define custom properties within a `:root` selector, which represents the highest level parent and enables the property to be accessed globally.

```css
:root {
  --primary-color: #333;
  --spacing-small: 8px;
  --font-stack: 'Roboto', sans-serif;
}
```

2. Use the `var()` function to apply these custom properties to elements.

```css
body {
  font-family: var(--font-stack);
  color: var(--primary-color);
}

.padding-small {
  padding: var(--spacing-small);
}
```

## Creating Utility Classes

For utility classes:

1. Identify common patterns in your design like margin, padding, text alignment, etc.
2. Create classes that serve single purposes, naming them in a clear and concise manner.

```css
.mt-10 {
  margin-top: 10px;
}

.text-center {
  text-align: center;
}

.bg-primary {
  background-color: var(--primary-color);
}
```

## Best Practices

- When naming custom properties, use a consistent naming convention that reflects your project's architecture or design system.
- Keep utility classes simple and avoid combining multiple styles that aren't typically used together.
- Document your custom properties and utility classes to ensure team members understand their purpose and use.

## Examples

Here's an example of how you can use custom properties and utility classes together:

HTML:

```html
<button class="btn bg-primary text-white">Click me</button>
```

CSS:

```css
:root {
  --primary-color: blue;
  --text-white: #fff;
}

.bg-primary {
  background-color: var(--primary-color);
}

.text-white {
  color: var(--text-white);
}

.btn {
  padding: 10px 20px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}
```

## Contributing

When contributing to this repository, please:

- Discuss proposed changes via issue before making a pull request.
- Update the README.md with details of changes to the interface or design system.
- Maintain the quality of the utility classes and custom properties.

For major changes, please open an issue first to discuss what you would like to change. Ensure to update tests as appropriate.

---

Remember to tailor this README to the specifics of your project and team needs. Documentation should always serve as a clear guide for others who may need to understand and work with your codebase.
